# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gokul/playground/secverilog/i2c_ift/examples/verification/i2cmaster/i2cmaster.cache/wt [current_project]
set_property parent.project_path /home/gokul/playground/secverilog/i2c_ift/examples/verification/i2cmaster/i2cmaster.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/gokul/playground/secverilog/i2c_ift/examples/verification/i2cmaster/i2cmaster.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/gokul/playground/secverilog/i2c_ift/examples/verification/i2cmaster/i2cmaster.srcs/sources_1/imports/i2cmaster/I2C_master.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top I2C_master -part xc7z020clg400-1


write_checkpoint -force -noxdef I2C_master.dcp

catch { report_utilization -file I2C_master_utilization_synth.rpt -pb I2C_master_utilization_synth.pb }
